# Test dockerfile to build terraform
# Linux x64
FROM hashicorp/terraform:full

LABEL maintainer="al@amarlanda.com"

# Install Node and NPM
#RUN apk add --update nodejs nodejs-npm

# Copy app to /src
#COPY . /src

#WORKDIR /src

# Install dependencies
#RUN  npm install

#RUN make /app
#CMD terraform build
