sudo apt-get install -y bind9

# /etc/bind/named.conf.options

options {
  directory "/var/cache/bind";
  listen-on port 53 { localhost; 10.0.0.0/24; };
  allow-query { localhost; 10.0.0.0/24; };
  #forwarders { 192.168.11.1; };
  recursion yes;
}

zone "amarlanda.com" IN {
  type master;
  file "amarlanda.com.zone";
};

$TTL 86400

@ IN SOA amarlanda.com root.amarlanda.com (
  2017062705
  3600
  900
  604800
  86400
)

@      IN NS server
server IN A  10.0.0.0
client IN A  192.168.11.87

named-checkconf validates /etc/bind/named.conf and included files.

$ named-checkconf

named-checkzone validates zone file.

$ /usr/sbin/named-checkzone hiroom2.com /var/cache/bind/hiroom2.com.zone
zone hiroom2.com/IN: loaded serial 2017062705
OK

4 Run BIND
Run BIND with systemd.

sudo systemctl enable bind9
sudo systemctl start bind9
5 Excution result
Run the following on client.

Make /etc/resolv.conf to refer DNS server.

$ cat /etc/resolv.conf
# Generated by NetworkManager
search hiroom2.com
nameserver 192.168.11.79
