apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins01
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.1.16
  name: jenkins01
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/jenkins01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: pvc-4a6ab012-7410-11e9-9092-42010a9a0183
status: {}
