pipeline {
  agent any
  stages {
    stage('gitclone') {
      steps {
        sh 'nslookup google.co.uk'
        git remote set-url origin git@github.com:Amarlanda/publis-spaient-demo.git
        git(poll: true, url: 'https://github.com/Amarlanda/publis-spaient-demo.git')
        #
      }
    }
  }
}
