apiVersion: v1
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 48 --retry-delay 10 jenkins01:8080/login
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jenkins01-tests
  selfLink: /api/v1/namespaces/default/configmaps/jenkins01-tests
