apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"backend"},"name":"backend","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000},{"name":"prometheus","port":9464,"targetPort":9464}],"selector":{"app":"backend"}}}
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  selfLink: /api/v1/namespaces/default/services/backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: prometheus
    port: 9464
    protocol: TCP
    targetPort: 9464
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
