apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"frontend"},"name":"frontend","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000},{"name":"prometheus","port":9464,"targetPort":9464}],"selector":{"app":"frontend"}}}
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  selfLink: /api/v1/namespaces/default/services/frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: prometheus
    port: 9464
    protocol: TCP
    targetPort: 9464
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
