apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins105
    chart: jenkins-0.38.0
    component: jenkins105-jenkins-master
  name: jenkins105-agent
  selfLink: /api/v1/namespaces/default/services/jenkins105-agent
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: jenkins105-jenkins-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
