apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins105
    chart: jenkins-0.38.0
    component: jenkins105-jenkins-master
    heritage: Tiller
    release: jenkins105
  name: jenkins105
  selfLink: /api/v1/namespaces/default/services/jenkins105
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins105-jenkins-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
