apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins01
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.1.21
  name: jenkins01-agent
  selfLink: /api/v1/namespaces/default/services/jenkins01-agent
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins01
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
