apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pilfering-horse-jenkins
    chart: jenkins-0.38.0
    component: pilfering-horse-jenkins-master
  name: pilfering-horse-jenkins-agent
  selfLink: /api/v1/namespaces/default/services/pilfering-horse-jenkins-agent
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: pilfering-horse-jenkins-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
