apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: yummy-crocodile-jenkins
    chart: jenkins-0.38.0
    component: yummy-crocodile-jenkins-master
    heritage: Tiller
    release: yummy-crocodile
  name: yummy-crocodile-jenkins
  selfLink: /api/v1/namespaces/default/services/yummy-crocodile-jenkins
spec:
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    nodePort: 32382
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: yummy-crocodile-jenkins-master
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
