apiVersion: v1
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 48 --retry-delay 10 dsf-jenkins:8080/login
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dsf-jenkins-tests
  selfLink: /api/v1/namespaces/default/configmaps/dsf-jenkins-tests
