apiVersion: v1
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 48 --retry-delay 10 pilfering-horse-jenkins:8080/login
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pilfering-horse-jenkins-tests
  selfLink: /api/v1/namespaces/default/configmaps/pilfering-horse-jenkins-tests
