apiVersion: v1
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 48 --retry-delay 10 yummy-crocodile-jenkins:8080/login
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: yummy-crocodile-jenkins-tests
  selfLink: /api/v1/namespaces/default/configmaps/yummy-crocodile-jenkins-tests
