apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: jenkins105
    chart: jenkins-0.38.0
    heritage: Tiller
    release: jenkins105
  name: jenkins105
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/jenkins105
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: pvc-072ce707-60a5-11e9-a710-42010a9a0165
status: {}
