apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: yummy-crocodile-jenkins
    chart: jenkins-0.38.0
    heritage: Tiller
    release: yummy-crocodile
  name: yummy-crocodile-jenkins
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/yummy-crocodile-jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: pvc-25022d5b-60a0-11e9-9f58-42010a9a001c
status: {}
