apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::355555488900:role/atlas20190519125640825500000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    mapUsers: |
    - userarn: arn:aws:iam::355555488900:user/amar
      username: admin
      groups:
        - system:masters
